export const FETCH_TRANSCRIPT_REQUEST = "FETCH_TRANSCRIPT_REQUEST";
export const FETCH_TRANSCRIPT_SUCCESS = "FETCH_TRANSCRIPT_SUCCESS";
export const FETCH_TRANSCRIPT_FAILURE = "FETCH_TRANSCRIPT_FAILURE";
